spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  redis:
    host: localhost
    port: 6379
  
  kafka:
    client-id: kafka-api-producer
    producer:
      bootstrap-servers: localhost:9092
      
      
  session:
    store-type: redis
      
server:
  port: 8081
  servlet:
    context-path: /api-kafka/

demo_ia_back:
  realm: demo_ia_back
  rabbitmq:
    queue: demo_ia_back_queue
    exchange: demo_ia_back_exchange
    topic:
      routing_key: email_sent_event
  kafka:
    topic:
      routing_key: email_sent_event_kafka
      routing_key_admin: email_sent_event_kafka_admin
   